version: '3.8'

services:
  # IPFS Node
  ipfs:
    image: ipfs/go-ipfs:v0.21.0
    container_name: peaq-ipfs
    ports:
      - "4001:4001"   # IPFS API
      - "5001:5001"   # IPFS Gateway
      - "8080:8080"   # Web UI
    volumes:
      - ipfs-data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
    command: daemon --migrate=true --agent-version-suffix=docker
    restart: unless-stopped

  # Nginx Reverse Proxy for IPFS
  nginx:
    image: nginx:alpine
    container_name: peaq-ipfs-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ipfs
    restart: unless-stopped

volumes:
  ipfs-data:
