services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ${NGINX_CERTS_HOST_PATH}:/etc/nginx/certs:ro
    depends_on:
      - ipfs
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 443 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  ipfs:
    image: ipfs/kubo:${IPFS_VERSION}
    container_name: ${PROJECT_NAME}-kubo
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - IPFS_PROFILE=${IPFS_PROFILE}
      - IPFS_SWARM_TCP=${IPFS_SWARM_TCP}
      - IPFS_DOMAIN=${IPFS_DOMAIN}
      - PUBLIC_IP=${PUBLIC_IP}
    entrypoint: ["/bin/sh","-lc","/docker-entrypoint.sh"]
    command: ["/usr/local/bin/start_ipfs"]
    volumes:
      - ${IPFS_DATA}:/data/ipfs
      - ${IPFS_DATA}/export:/export
      - ./scripts/ipfs-entrypoint.sh:/docker-entrypoint.sh:ro
    expose:
      - "${IPFS_GATEWAY_PORT}"
      - "${IPFS_API_PORT}"
    ports:
      - "${PUBLISHED_SWARM_TCP}:${IPFS_SWARM_TCP}/tcp"
      - "${PUBLISHED_SWARM_UDP}:${IPFS_SWARM_TCP}/udp"
    healthcheck:
      test: ["CMD-SHELL", "ipfs swarm peers >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  ipfs_data:
