version: '3.8'

services:
  # IPFS Node (internal-only, exposed via nginx)
  ipfs:
    image: ipfs/go-ipfs:v0.21.0
    container_name: peaq-ipfs
    environment:
      - IPFS_PROFILE=server
    command: daemon --migrate=true --agent-version-suffix=docker
    volumes:
      - ipfs-data:/data/ipfs
    restart: unless-stopped

  # Nginx Reverse Proxy for IPFS
  nginx:
    image: nginx:alpine
    container_name: peaq-ipfs-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/ssl:/etc/nginx/ssl
      - ./configs/auth-ips.conf:/etc/nginx/auth-ips.conf:ro
      - ./configs/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - ipfs
    restart: unless-stopped

volumes:
  ipfs-data:
